// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWk8iWZtj76Z27WdapxEU8b_4j6o25M_o',
    appId: '1:671461936114:web:c8ba547b2c6057f927796b',
    messagingSenderId: '671461936114',
    projectId: 'whatsapp-clone-ff593',
    authDomain: 'whatsapp-clone-ff593.firebaseapp.com',
    storageBucket: 'whatsapp-clone-ff593.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYJ9qqU0soYqJN7gcE_0Dgp8A-8dLO15k',
    appId: '1:671461936114:android:566afb4a28af79e827796b',
    messagingSenderId: '671461936114',
    projectId: 'whatsapp-clone-ff593',
    storageBucket: 'whatsapp-clone-ff593.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4_aFeQWtuhm1iC_R8wekCMLiDrgL_HQ0',
    appId: '1:671461936114:ios:6f167c76a39f4dd527796b',
    messagingSenderId: '671461936114',
    projectId: 'whatsapp-clone-ff593',
    storageBucket: 'whatsapp-clone-ff593.appspot.com',
    iosBundleId: 'com.example.untitledz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4_aFeQWtuhm1iC_R8wekCMLiDrgL_HQ0',
    appId: '1:671461936114:ios:6f167c76a39f4dd527796b',
    messagingSenderId: '671461936114',
    projectId: 'whatsapp-clone-ff593',
    storageBucket: 'whatsapp-clone-ff593.appspot.com',
    iosBundleId: 'com.example.untitledz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWk8iWZtj76Z27WdapxEU8b_4j6o25M_o',
    appId: '1:671461936114:web:1484b891bdbacf6327796b',
    messagingSenderId: '671461936114',
    projectId: 'whatsapp-clone-ff593',
    authDomain: 'whatsapp-clone-ff593.firebaseapp.com',
    storageBucket: 'whatsapp-clone-ff593.appspot.com',
  );
}
